### ISSUE TITLE
this is not threads, this is a process pool

### ISSUE THREAD

**Issue by ORESoftware** [avoidwork/tiny-worker#1]
Please add a caveat/disclaimer that says that this uses child_processes not webworker threads! :)

I saw that node-webworker-threads referred people to this lib, but this does not do the same thing at all.

**Comment by avoidwork** [comment]
node doesn't have threads.

**Comment by avoidwork** [comment]
well, it's posix threads for the child process ... but i get what you mean. the point of the lib is to mimic the api so the dev doesn't have to think in two contexts: https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker

**Comment by ORESoftware** [comment]
Yeah I see, I understand...Node has threads because Chrome supports native threads, because Chrome supports the WebWorker API

**Comment by ORESoftware** [comment]
all I can say is a threadpool and processpool are just different things

**Comment by avoidwork** [comment]
Where's that thread api documentation? https://nodejs.org/docs/latest-v0.12.x/api/

I don't think you know what you're talking about in this case. It's not exposed via node.js, this is why things like 'fibers' happened early on.

**Comment by avoidwork** [comment]
I also make no claim that this is using "threads", which are simply a scheduling abstraction. This is better.

**Comment by ORESoftware** [comment]
I am aware that the Node core API does not expose threads which is a shame. (Although you did link to 0.12, which is several versions old.) But libraries such as 

https://www.npmjs.com/package/webworker-threads

are able to do some magic to access the native threads in V8. What do you think of that?

Here are some thoughts:
1. You use threads on the front-end and process pooling on the backend, this is inherently not a mirroring and is a mismatch. 
2. The lib is called tiny-worker which suggests threads not processes
3. the **node-webworker-threads** docs link to this lib "if you want to use 'require' to load code (in a webworker)", so I was really excited to see that someone had allowed for backend webworkers (threads) to use require, but it was too good to be true.
4. I agree that processes are sometimes better than threads, _however_ JS webworkers are a super nice version of threads because they are not pre-emptive and they do message passing. This makes them _super convenient_ compared to Java or C# threads.

Please just make it clear in your docs that it's a process pool in Node and not threads, that's all I can ask. Thanks and sorry to be irritating.

**Comment by avoidwork** [comment]
not going to happen.

**Comment by ORESoftware** [comment]
you do you

**Comment by avoidwork** [comment]
locking now.
