### ISSUE TITLE
Is it possible to require other nodejs modules within the worker function?

### ISSUE THREAD

**Issue by andrelanger** [avoidwork/tiny-worker#10]
Hi Jason,

First of all: Great work, tiny-worker is handy and works as expected.

I just asked myself if it is possible to reference other nodejs components from the same project within the worker function.
So I would like to do something like

var component = require('../anothermodule');

    var worker = new Worker(function () {
        self.onmessage = function (ev) {

            console.log(component.dosomething());
            postMessage("blafoo");
        };
    });

However, as soon as I try something like that the postMessage command in the worker function is not reached at all. I assume that I do not entirely understand the Web Worker concept and that I can only use project-independent JS code in the Worker function.

I appreciate any brief feedback

André

**Comment by Lindenk** [comment]
From what I've noticed, `__dirname` is set to `{projectbase}/node_modules/tiny-worker/lib`. A quick hack to get around the problem is to reference everything from `__dirname + "/../../../path/to/module"`. Of course, an actual solution would be better.

**Comment by avoidwork** [comment]
Would `process.cwd()` be applicable? I get the feeling I need to expose the options for the child ps so it can be customized, but that also gets out of sync with the worker API of the client :/

**Comment by avoidwork** [comment]
2.0.0 exposes the `args` & `options` of `child_process.fork()`.

**Comment by wmertens** [comment]
Would it not be possible to set __dirname to the location of the script? If passed a function, you can use http://stackoverflow.com/a/29581862/124416 to get that.

**Comment by avoidwork** [comment]
@wmertens the problem with these solutions is they're for single use cases; so exposing `args` &  `options` lets you do whatever you need, or it defaults to node's natural behavior.

**Comment by wmertens** [comment]
But node's natural behavior is to have __dirname be the directory of the
file, not of the worker.js :)

**Comment by avoidwork** [comment]
@wmertens oh yeah, i see what you mean. line 44/45 seems like a left over mistake.

**Comment by avoidwork** [comment]
gotcha, now it defaults to the `process.cwd()` of the script that requires it, and you can override via the third parameter (see child_process.fork() on nodejs.org documentation)

**Comment by avoidwork** [comment]
> But node's natural behavior is to have __dirname be the directory of the
file, not of the worker.js :)

how could this script possibly know the location of anything you might require inside of it via a closure? the `__dirname` property being set to the worker.js is the default behavior everyone's talked about, but it's not in the ctx they're thinking of.

from https://nodejs.org/docs/latest/api/globals.html#globals_dirname

```
__dirname#
Added in: v0.1.27
<String>
The directory name of the current module. This the same as the path.dirname() of the __filename.

__dirname is not actually a global but rather local to each module.
```

hence, what everyone wants is not `__dirname`, but to specify the `cwd` such that their requires will work with npm properly.

**Comment by avoidwork** [comment]
**The directory name of the current module. This the same as the path.dirname() of the __filename.**

^ that is not _your_ script, that is my script / this lib; even changing `__dirname` to be `process.cwd()` is weird, may have a side effect I haven't considered yet.

**Comment by avoidwork** [comment]
@wmertens I just realized, you guys are building relative paths aren't you? instead of `path.join()` or `path.resolve()` with `process.cwd()`, you're doing something like `require(__dirname + '../../../')` right? I can't support that. No one can, it doesn't even work properly across OSes in some cases.

**Comment by wmertens** [comment]
@avoidwork yes relative paths, it works everywhere in Node :)

You can do it if you set `__dirname` to the path of the script with the given function, so that in the script you can do `require(path.join(__dirname, 'myOtherScriptFile))`. You can find the path of the given function by using http://stackoverflow.com/a/29581862/124416.

For workers in scripts, you could `require()` them in your worker wrapper function instead of reading them and running them in your context. Then Node would resolve normally.

(BTW, awesome module, I had some cpu-bound perf issues with a server and I was able to make it multi-process in 1.5 hours, it's happy now)

**Comment by avoidwork** [comment]
@wmertens you can include n+ files to run & `__dirname` doesn't exist in a vm state for a child_process, so there is literally no way to accomplish it when you consider shared state.

**Comment by avoidwork** [comment]
@wmertens i welcome a pull request for this functionality, but i will not be spending any time on it because it's someone else' problem.

**Comment by wmertens** [comment]
Fully understand! No time to spend on this right now, but possibly soon.
Including many files is just a matter of running `require()` multiple files
in your worker initialization; `__dirname` will be set correctly in every
file you require and your worker init doesn't use it. All that is needed is
that the files are passed to you with absolute paths (caller can use
`require.ensure()`)

**Comment by avoidwork** [comment]
@wmertens when passing a file path, yes this is easily done, but when you consider `importScripts()` it gets less clear; do they inherit from the first file? what if you pass a function and then import scripts? etc.

**Comment by wmertens** [comment]
importScripts would simply do `files.forEach(require)`, no?

**Comment by wmertens** [comment]
importScripts is not documented though, what is it for?

**Comment by avoidwork** [comment]
It's a `WorkerGlobalScope` method; this _is_ a WebWorker compatible API. Things that cannot exist are not provided, like `navigator`.

**Comment by wmertens** [comment]
Aha. So can that not be a forEach to require()?

**Comment by avoidwork** [comment]
> Aha. So can that not be a forEach to require()?

No, as I've mentioned this is not running in the context you assume it is. This is the current signature:

```
global.importScripts = (...files) => {
		if (files.length > 0) {
			vm.createScript(files.map(file => fs.readFileSync(file, "utf8")).join("\n")).runInThisContext();
		}
	};
```

Functionally this is close to a require, but it requires you to provide a valid path (absolute path is ideal, relative is now going to be relative to `process.cwd()` or whatever you specify).

**Comment by dseeker** [comment]
@avoidwork it's not clear to me if it's possible to use the existing imported modules from the main function to the worker function, could you clarify?

using the original example
```
var Worker = require("tiny-worker");
var p = require('path')
var worker = new Worker(function () {
	self.onmessage = function (ev) {
		postMessage(p.resolve('.'));
	};
});

worker.onmessage = function (ev) {
	console.log(ev.data);
	worker.terminate();
};

worker.postMessage("Hello World!");
```

I've also tried to pass p = require('path') inside of the worker function but the result is the same. 
Is the only way of importing modules via external js file? or can this be done with inline functions?

**Comment by avoidwork** [comment]
@dseeker the 'worker' function exists in a vm context separate from the main process (it's a child process), which has some of the node globals decorated such that they work, e.g. `require()`. You do not gain access to 'main' function/script via lexical scope (that'd be a neat trick, but diff vm...).
