### ISSUE TITLE
redundant `this.method.call(this)`

### ISSUE THREAD

**Issue by hville** [avoidwork/tiny-worker#12]
The pattern `this.method.call(this, arg)` is found in a number of places:
* [index.js#L21](https://github.com/avoidwork/tiny-worker/blob/master/src/index.js#L21)
* [index.js#L30](https://github.com/avoidwork/tiny-worker/blob/master/src/index.js#L30)
* [index.js#L37](https://github.com/avoidwork/tiny-worker/blob/master/src/index.js#L37)

It could be simplified to `this.method(arg)`.
I can do a PR if there is any interest

**Comment by avoidwork** [comment]
Not interested, you can set a bound function.

**Comment by hville** [comment]
No need for any bounding, it is already called from the right context.

**Comment by avoidwork** [comment]
You're not understanding what I'm saying.
