### ISSUE TITLE
redundant JSON.stringify call

### ISSUE THREAD

**Issue by hville** [avoidwork/tiny-worker#13]
Is there a reason why JSON.stringify is called when sending messages? 
* [worker.js#L31](https://github.com/avoidwork/tiny-worker/blob/master/src/worker.js#L31)
* [worker.js#L35](https://github.com/avoidwork/tiny-worker/blob/master/src/worker.js#L35)
* [index.js#L51](https://github.com/avoidwork/tiny-worker/blob/master/src/index.js#L51)

I understand `process.send(...)` already uses JSON.stringify under the hood so the message gets stringified and parsed twice.

**Comment by avoidwork** [comment]
This is not redundant; the signature of `child_process._send()` does not specify 0 padding; when transferring large JSON strings this matters.

https://github.com/nodejs/node/blob/db1087c9757c31a82c50a1eba368d8cba95b57d0/lib/internal/child_process.js#L626

**Comment by hville** [comment]
The standard for `JSON.stringify` states that 0 padding is the default. In effect `JSON.stringify(obj)` is the same as `JSON.stringify(obj, null, 0)`.
I've just did a quick test in node and sure behaves this way. Unless this is to cover for some old bug in previous node versions...

**Comment by avoidwork** [comment]
Yup, you're right. Doesn't change that I write explicit code.
