### ISSUE TITLE
Debug Ports with more than one layer

### ISSUE THREAD

**Issue by moosbruggerj** [avoidwork/tiny-worker#16]
I've found an error in the code for calculating new debug ports, and the handling of process.execArgs. There is already a fix for that, but while looking into this, there was another problem.
If a process has 2 childs, and the first of them creates another child process, 2 processe get the same debug port and the program crashes

```
1234
||
|-1235
|  |
|  -1236
-1236
```

A possible solution for this would be to have a higher offset, but this solution has also that same problem at some point.
```
1234
||
|-1334
|  ||
|  |-1434
|  --1435
-1335
  |
  -1435
```

I tried to use process.pid in the calculation, but if you are using an IDE like WebStorm debug Ports already start very high and in a few steps ports are too high.
Another possible way would be to randomize the offset for each process
e.g. `newPort = oldPort + Math.random() * 100 + 100 + forkedChilds;` where the random value is calculated at init of `tiny-worker`. But I'm not really happy with that solution.

Suggestions?

**Comment by moosbruggerj** [comment]
a possibility could be to try and bind the calculated port, if it doesn't succeed, try another one

**Comment by avoidwork** [comment]
This is a tangent I was hoping to avoid entirely; randomly grabbing a port may work sometimes but is also a delayed collision.

You would need to define the behavior, the expectation & the documentation to explain whatever you attempt. It should scale outside of your use cases, otherwise it's not high value and probably shouldn't be in the module.

**Comment by avoidwork** [comment]
A default range & override might be okay, if well documented.

**Comment by avoidwork** [comment]
@dude8 are you confident you solved the problem with #17?

**Comment by moosbruggerj** [comment]
well, I'm as confident as I can get without building a more advanced system to calculate ports, wich would include either port testing or ipc communication with childs and parents. And such a system would cost execution time and make tiny-worker much more complicated, wich is not worth it for a non-core feature imho.

**Comment by avoidwork** [comment]
ok, imma version bump and release 👍
