### ISSUE TITLE
Worker collides with node stdlib

### ISSUE THREAD

**Issue by fridgerator** [avoidwork/tiny-worker#23]
the `Worker` class here collides with https://nodejs.org/api/cluster.html#cluster_class_worker

It can be import as a different name `import { Worker as TinyWorker } from 'tiny-worker'`, however I was trying to write a typescript declaration file for this library and was running into issues with the `Worker` class `Duplicate identifier 'Worker'`

```typescript
declare module "tiny-worker" {
  export class Worker {

  }
}
```

**Comment by avoidwork** [comment]
I don't use typescript; what's your proposed solution? This lib precedes core by over 3 years btw.

**Comment by fridgerator** [comment]
I guess this is just a warning and not an error, I am still able to use the typescript definition.

So for now I guess we dont need a solution, I'll go ahead and close the issue.

Thanks for the fast response, and thanks for this library also!

**Comment by avoidwork** [comment]
Changing the constructor to be `TinyWorker` instead of `Worker` would be a major version bump, but not a big deal from my pov. Is there an alternative?
