### ISSUE TITLE
child process exits prematurely when running web server

### ISSUE THREAD

**Issue by ddombrowsky** [avoidwork/tiny-worker#24]
I have a process that starts a web server in a separate process using `tiny-worker`:
```
    const worker = new Worker(() => {
...
      self.onmessage = function(event) {
            server = require(event.data.serverjs);
            server.configure(event.data.locator);
            server.startServer()
        }
```
`startServer` starts a standard node express listener on a port.

For the life of me, I just CAN'T that process to hang around.  It'll serve up requests for a while (sometimes 1, sometimes 100) but then exits.  I can't find an exception.  I can't find an error.  My workaround is to catch the "exit" and restart:
```
    workerThread.child.on('exit', (code) =>
        workerThreadRestart(
            code, serverjs, locator, sessionId, ua,
    ));
```

FWIW `code` is always `null`, so it seems that the child process is not exiting cleanly.

I've tried catching signals, errors, everything that I can think of.  Nothing keeps that process alive.  

Any ideas on how to debug this?  I'm using `    "electron-prebuilt-compile": "2.0.4",` which I think has node 8.9.

**Comment by avoidwork** [comment]
I'll have to look this over... off the top of my head I have no idea why it'd be exiting. I've used it in electron but not in this way.

**Comment by ddombrowsky** [comment]
@avoidwork I'm not confident it's a bug in `tiny-worker`, or in `express`, or in my code.  I'm just wondering how else to try and discover the root cause.  I've tried adding busy loops with `setTimeout` in the child process, so the node event loop is never empty, but that doesn't seem to fix anything.

**Comment by ddombrowsky** [comment]
This issue can be closed, it was pretty much transient.  I never discovered the root cause, but I suspect it was some exception deep in the code that wasn't being handled or reported.

**Comment by avoidwork** [comment]
I use a similar approach in a few things I've made after you opened this ticket; it's always something below the water line. Migrating to the native Worker in the newer versions of node.js should net similar behavior (problem wise i mean).
