### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by Alynva** [avoidwork/tiny-worker#25]
https://github.com/avoidwork/tiny-worker/blob/bc1edc83861d46510aff57ade4ddeb40541ae054/lib/index.js#L31

doing a little hack...

``` js
var debugVars = process.execArgv ? process.execArgv.filter(function (execArg) {
	return (/(debug|inspect)/.test(execArg));
}) : [];
```

I got this another error:

**TypeError: fork is not a function**

https://github.com/avoidwork/tiny-worker/blob/bc1edc83861d46510aff57ade4ddeb40541ae054/lib/index.js#L75

Someone can help?

**Comment by avoidwork** [comment]
Hi @Alynva, what's the point of the change? `process.execArgv` is always an array.

**Comment by Alynva** [comment]
Hello, I'm using React and I don't know what I'm doing wrong.

**Comment by Alynva** [comment]
Googling it, I found this comment: https://github.com/facebook/create-react-app/issues/3032#issuecomment-326929235

Than I suppose that tiny-worker is only for NodeJS and not to use in browser environment.

**Comment by avoidwork** [comment]
ah, yes that is the case. it was meant to mimic a `Worker` for node.
