### ISSUE TITLE
Pass arguents to worker

### ISSUE THREAD

**Issue by galvaniccoffee** [avoidwork/tiny-worker#26]
Hi! :)

I need to pass simple arguments to a worker. Somewhat like that:
```javascript
max = 42;

var w = new Worker(function () {
    for (var i = 0; i < max; i++) {
        // Do something...
    }
}
```

`max` is in a different context than what is accessible from within the worker. How can I pass its value (or alternatively, the main context) to the worker?

The only way I would see is to use `w.postMessage(max)` after creating `w`, and have the thread inside of `w` block until it receives this first message. But that seems rather inelegant.

**Comment by BlessYAHU** [comment]
You could capture the value in the function:

```
max = 42;

var w = new Worker(function () {
   var maximum = max; 'or just the value
    for (var i = 0; i < maximum; i++) {
        // Do something...
    }
}
```

**Comment by galvaniccoffee** [comment]
Thank you! I've never heard of this mechanism before.
When I try it though, I just get a `ReferenceError: max is not defined` from the line `var maximum = max;`.
Also, could you explain what you mean by `'or just the value`?

**Comment by BlessYAHU** [comment]
Sorry, you have to use let not var in the function to capture the value of max in the function scope.  This should work.

max = 42;

var w = new Worker(function () {
   let maximum = max; 
   'or just the value let maximum = 42;
    for (var i = 0; i < maximum; i++) {
        // Do something...
    }
}

**Comment by galvaniccoffee** [comment]
Sorry, but that doesn't seem to change anything. It still throws a `ReferenceError` :(

**Comment by BlessYAHU** [comment]
You're right.  That doesn't work with workers.  You will probably need to pass in the argument with a post message (I verified this worked by running it):

```
var Worker = require("tiny-worker");

var x = 3;
var fun = function (max) {
    let a = max;
    let maxi = a;
    for (var i = 0; i < maxi; i++) {
        console.log(i)
    }
};

var w = new Worker(function() {
    self.onmessage = function (ev) {
        postMessage(ev.data);
    }
});

w.onmessage = function(ev) {
    fun(ev.data);
    w.terminate();
}

w.postMessage(x);
```

**Comment by moosbruggerj** [comment]
another method would be to pass the arguments in the `args` parameter like in `child_process.fork()` of the node.js api, form which the worker class is derived. (https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) 

this should roughly look like this:
```javascript
let Worker = require("tiny-worker");

let max = 42;
let w = new Worker(function() {
    console.log(process.argv)
}, [max]);

//or with execArgv
let w2 = new Worker(function() {
    console.log(process.execArgv);
}, [], {execArgv: [max]});
```
The reason this is needed, is because the function inside the Worker definition is created and executed in another process, where the max variable doesn't exist. (therefore the ReferenceError)
So the value must explicitly be passed, if you want a more reference style variable (e.g. updating on change), you need to solve that via messages, with getters and setters.

**Comment by avoidwork** [comment]
Hi,

You'd do it the same as you would with a browser `Worker`; you'd `postMessage()` data between the domains. See https://github.com/avoidwork/tiny-worker#creating-a-worker-from-a-function for an example.

**Comment by galvaniccoffee** [comment]
Thank you all for your help!
I still have some questions, unfortunately, but these probably exceed this thread. I will ask them elsewhere.

**Comment by avoidwork** [comment]
feel free to start a new issue, someone might be able to help.
