### ISSUE TITLE
Use worker_threads if available

### ISSUE THREAD

**Issue by karelbilek** [avoidwork/tiny-worker#27]
New node has experimental support for workers

https://nodejs.org/api/worker_threads.html

but OF COURSE they are just TINY different from webworkers so they cannot be used as drop-in, as this module can be used.

Maybe this module can use worker_threads when available?

**Comment by avoidwork** [comment]
Yeah! I don't see why not. When that work started it seemed like a natural sunset to this one, but the interop is handy. Slim chance that I put effort into it before end of year, but good chance in q1 you see movement here.

**Comment by avoidwork** [comment]
Closing, as this is already done via https://github.com/andywer/threads.js that falls back to tiny-worker.
