### ISSUE TITLE
How to detect if child has exited?

### ISSUE THREAD

**Issue by mifi** [avoidwork/tiny-worker#28]
If I run process.exit() in the child or it crashes, how can I know?

**Comment by avoidwork** [comment]
hi,

nothing handles an explicit `exit`, or `disconnect`; this lib targets the `Worker` API and nothing else. those events could be added, but that's not what I was aiming for with this lib.

https://developer.mozilla.org/en-US/docs/Web/API/Worker

**Comment by avoidwork** [comment]
Would wiring `exit` to `error` suffice?

**Comment by mifi** [comment]
Oh ok, sorry I didn't realise that this was written to adhere to Worker API. I decided to write my own wrapper around child_process.fork, because my use case was more like "Run a piece of code in a different process and give me a promise that resolves if it succeeds, or reject if anything goes wrong" [fork-worker](https://github.com/mifi/fork-worker)
You can close this if you want.
