### ISSUE TITLE
Is worker.onerror() not working?

### ISSUE THREAD

**Issue by leaf-node** [avoidwork/tiny-worker#4]
How is `worker.onerror()` supposed to work?

The following doesn't print the "error detected" message. It prints the stack trace and then exits with a return value of `0`.

``` javascript
onmessage = function (ev) {
    throw new Error('test');
};
```

``` javascript
var Worker = require("tiny-worker");
var worker = new Worker("repeat.js");

worker.onerror = function (ev) {
    console.log("error detected");
    console.log(ev.data);
    worker.terminate();
    process.exit(1);
};

worker.postMessage("Hello World!");
```

I'm using nodejs v4.5.0

**Comment by leaf-node** [comment]
Here's the stack trace:

```
evalmachine.<anonymous>:2
    throw new Error('test');
    ^

Error: test
    at onmessage (evalmachine.<anonymous>:2:11)
    at process.<anonymous> (/home/andrew/jstest/workers3/node_modules/tiny-worker/lib/worker.js:67:54)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at internal/child_process.js:696:12
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by avoidwork** [comment]
Looks like it's out of sync now; the event it was wired to no longer exists for 4.x+

https://github.com/avoidwork/tiny-worker/blob/master/src/worker.js#L64

I'll update it tomorrow.

**Comment by avoidwork** [comment]
This wasn't out of sync; it was expected that the developer handle the error properly. However, it's reasonable to expect it to bubble as per the `Worker` spec, so that's the default behavior now.
