### ISSUE TITLE
require('./local_script.js'); not working

### ISSUE THREAD

**Issue by leaf-node** [avoidwork/tiny-worker#5]
Worker scripts are able to `require()` builtin modules and those in the local `node_modules` directory, but they cannot require files specified with a relative path such as `./local_script.js`.

I also noticed that the `__filename` variable is not defined in worker scripts.

I would like worker scripts to require files relative to the directory of the worker scripts themselves, not relative to the directory of the running program's source file, any third party libraries that load workers with tiny-workers, or the working directory. Such behavior seems to be aligned with nodejs style `require()` functionality.

**Comment by avoidwork** [comment]
That would also mean exposing `__dirname`; these are not global variables btw. Node's require wraps the module in a function with the `__*` variables as arguments. Easily added; you can contribute these changes btw; that's why it's on github.

**Comment by avoidwork** [comment]
Your request for relative paths is inane; it's up to you to set the appropriate path. As such, I've added `__filename` & `__dirname` to the context.

**Comment by avoidwork** [comment]
You should be using `path.join()` to create paths properly for all OSes.
