### ISSUE TITLE
Worker script loading rule is based on current working directory

### ISSUE THREAD

**Issue by leaf-node** [avoidwork/tiny-worker#6]
I'm not sure how this issue should be resolved, but here it is:

If i have a program `x.js` and it has a library dependency `y.js` installed through npm, and that uses `tiny-worker`, `x.js` can pass the name of a worker program it wants run by `y`. `worker.js` is in the same directory as `x.js`, so all is good.

However, if `x.js` is itself a library that is called by `z.js` or `x.js` is run from a current directory other than the parent directory of `x.js`, then `worker.js` is not found. This is because the finding rules for `worker.js` are based on the current directory. This is a problem because sometimes scripts are run from other places, such as one's home directory. Node scripts get installed in several places, and if `x` is to be used as a system executable, it will not work under most cases because the program needs to run regardless of one's current working directory.

I'm not sure what the correct solution is. For the sake of consistency with standard `require()` behavior, one might prefer to load relative to the the script that is calling `new Worker(...)`. However this is a problem if a library like `y.js` accepts the name of a worker as a parameter. If that is the case, it seems `x.js` cannot supply its own worker unless it places it in the same directory containing `y.js`, which would break isolation of components and make working with source code repositories less logical.

Perhaps I misunderstand the convention regarding things like `require('child_process').fork()`, but it seems as though none of the options I have considered (nor `tiny-worker`'s behavior) seem correct.

This is related to, but not the same issue as, issue #5.

**Comment by avoidwork** [comment]
Pass a valid path: https://github.com/avoidwork/tiny-worker/blob/master/src/worker.js#L24

**Comment by avoidwork** [comment]
If you need multiples, use `importScripts`: https://github.com/avoidwork/tiny-worker/blob/master/src/worker.js#L44
