### ISSUE TITLE
Error when running Node in debug mode

### ISSUE THREAD

**Issue by danieleds** [avoidwork/tiny-worker#8]
If I try to use this module with Node in debug mode (started with `node --debug --nolazy ./index.js`) I get the following error:

```
Error: listen EADDRINUSE :::5858
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at Agent.Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at net.js:1398:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by avoidwork** [comment]
Has nothing to do with tiny-worker.

**Comment by danieleds** [comment]
@avoidwork it actually has to do with tiny-worker.

Try your example:

```
var Worker = require("tiny-worker");
var worker = new Worker(function () {
    self.onmessage = function (ev) {
        postMessage(ev.data);
    };
});

worker.onmessage = function (ev) {
    console.log(ev.data);
    worker.terminate();
};

worker.postMessage("Hello World!");
```

And run it as I showed you.

**Comment by avoidwork** [comment]
do you understand that you're forking a process with a debugger attached?

pebcak.

**Comment by danieleds** [comment]
Uhm, yes, I do. That's the purpose of debuggers. Your module is breaking node standard behavior.

Are you going to repen the issue and start discussing about a solution, or not?

**Comment by avoidwork** [comment]
Last time I reply:

If you fork a process with a debugger attached, you're cloning the debugger & it's not shifting ports. This lib just wraps `child_process.fork()` and sets up the child env with enough functionality such that you can do stuff like a web worker.

This is native node behavior.

**Comment by danieleds** [comment]
I know, I've read the code before opening this issue. I'm not here to waste my time, and yours neither.

Just change [this line](https://github.com/avoidwork/tiny-worker/blob/master/src/index.js#L11) to:

```
this.child = fork(worker, [], {execArgv: []});
```

and it's fixed.

And as a personal suggestion: stop being a dick with the people who contribute to improve your work.

**Comment by avoidwork** [comment]
What did you contribute? You ate up my time with this little thread.

Suggestion: Don't be a bitch.

**Comment by dmccuskey** [comment]
thanks @danieleds for the solution, i had same issue when trying to attach a debugger. however, i needed to debug BOTH the parent and child processes. so i modified `tiny-worker` like so:

```
tiny-worker/index.js

	function Worker( arg, forkArgs, forkOpts ) {
		var _this = this;
		forkArgs = forkArgs || [];
		forkOpts = forkOpts || {};

...
		this.child = fork( worker, forkArgs, forkOpts );
```

this gives caller ability to send in custom debug ports, etc., something like the following:
(taken from a nodejs issue: https://github.com/nodejs/node-v0.x-archive/issues/5318)

```
my-server.js 

var activateChildDebugging = true
var childDebugPort = 5859

...
	var args = undefined
	var opts = undefined
	if (activateChildDebugging) {
		opts = {
			execArgv: ['--debug=' + childDebugPort]
			// execArgv: ['--debug-brk=' + childDebugPort]
		}
		console.log("Debugging Worker at port", childDebugPort)
		childDebugPort = childDebugPort + 1
	}
	const worker = new Worker( './user-worker.js', args, opts )
```

thanks to @avoidwork for `tiny-worker`.

**Comment by nicholaswmin** [comment]
Thanks @danieleds.

@avoidwork You are a pathetic excuse as a man but thanks for the module

**Comment by avoidwork** [comment]
@nicholaswmin 👍 you win at the internet

**Comment by nicholaswmin** [comment]
thanks cowboy

**Comment by avoidwork** [comment]
kinda curious, what's the basis for your personal attack? this feature was delivered with 2.0.0 months ago, so bringing this half-assed blame back from the dead accomplishes what? get a troll star or something?

**Comment by avoidwork** [comment]
I also dig how this project was effectively lifted by @danieleds, not forked, and modified to be equal to the 2.0; instead of just opening a PR with the feature you fragment this further. awesome.

**Comment by nicholaswmin** [comment]
Yeah don't cry over that either. Behaving like an angry autistic doesn't invite PR's

**Comment by avoidwork** [comment]
@nicholaswmin simmer down pot, this kettle isn't angry. if you look at any my other projects you'll see i welcome PRs, and tell assholes to fuck off if they blame me for something the _framework_ does. 

I'm not responsible for you guys knowing how shit works, or how to conduct yourselves such that a real contribution would be welcomed; what you did here is just reiterate the fucktard approach of blaming someone else for your problem.

**Comment by nicholaswmin** [comment]
Sure thing cowboy.

**Comment by avoidwork** [comment]
dude, this'll look so awesome on your profile long term.

**Comment by danieleds** [comment]
> Has nothing to do with tiny-worker.

> do you understand that you're forking a process with a debugger attached? pebcak

> What did you contribute? You ate up my time with this little thread.

(after a while...)

> this feature was delivered with 2.0.0 months ago

Seriously?
So can I shut down my fork now?

**Comment by avoidwork** [comment]
Yeah; all you ever had to do was open a PR with the feature you wanted to add.

https://github.com/avoidwork/tiny-worker/commit/a63db63a3a8437315fa70e56bbb99ccca18e378f

I accept ownership of bugs I produce, & I will argue default behavior. I don't even lock threads, because I find there's value over time revisiting requests or problems people bring my attention to, such as this one. You were I believe the first of 3 distinct asks, third strike (against the lib) I added the feature.

**Comment by avoidwork** [comment]
There is a caveat, because this is not in the ctx most people assume the default cwd is of the process that spawns the worker. It's not possible to solve it in such a way that works for everyone without removing the vm context which kinda breaks the API and would be a value hit.
