### ISSUE TITLE
Does not send Typed Arrays

### ISSUE THREAD

**Issue by metabench** [avoidwork/tiny-worker#9]
I have just tried using this to send a Float32Array to a worker thread. It arrives as an object where the keys represent the indexes.

Should the types of data that it sends be made clearer in the documentation?

Should better handling of typed array (and maybe buffer data) be on the development roadmap for this project?

**Comment by avoidwork** [comment]
You need to serialize to JSON to send, & back to a typed Array in your worker ps. This is a common problem when sending Objects between domains.
